name: My Custom Action

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: 22f3002903@ds.study.iitm.ac.in - Run a simple command
      run: |
        echo "This step has the specified email in its name."
        echo "Running some commands here..."

    - name: Another step
      run: echo "This is a subsequent step."
